"""empty message

Revision ID: 105adfcb4dfc
Revises: c301fcaa235c
Create Date: 2026-02-05 10:21:16.716115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105adfcb4dfc'
down_revision = 'c301fcaa235c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocking', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.drop_column('blocking')

    op.drop_table('calendar_series')
    # ### end Alembic commands ###
