"""2fa entries in User model

Revision ID: 153a88725401
Revises: 57b74656c425
Create Date: 2025-10-16 10:43:26.449187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153a88725401'
down_revision = '57b74656c425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is2fa_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('token_2fa', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['token_2fa'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_2fa')
        batch_op.drop_column('is2fa_enabled')

    # ### end Alembic commands ###
