"""make calendar event types into int column

Revision ID: 2c3e0eb6b32c
Revises: 999c889363a7
Create Date: 2026-03-02 11:58:06.197916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c3e0eb6b32c'
down_revision = '999c889363a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=False))
        batch_op.drop_column('public')
        batch_op.drop_column('school')
        batch_op.drop_column('special')
        batch_op.drop_column('misc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('misc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('special', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('school', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
