"""empty message

Revision ID: 35ad2406fa44
Revises: 105adfcb4dfc
Create Date: 2026-02-05 10:23:22.590535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ad2406fa44'
down_revision = '105adfcb4dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_calendar_entry_series_id'), ['series_id'], unique=False)
        batch_op.create_foreign_key(None, 'calendar_series', ['series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_calendar_entry_series_id'))
        batch_op.drop_column('series_id')

    # ### end Alembic commands ###
