"""Add profile pictures to User

Revision ID: 480c47f070cd
Revises: 514533e5915a
Create Date: 2025-02-17 00:35:11.097908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480c47f070cd'
down_revision = '514533e5915a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
