"""Add user related rights

Revision ID: 514533e5915a
Revises: 94fd8b420f38
Create Date: 2025-02-13 12:37:57.629330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514533e5915a'
down_revision = '94fd8b420f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_user', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('edit_user', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delete_user', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('edit_rights', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.drop_column('edit_rights')
        batch_op.drop_column('delete_user')
        batch_op.drop_column('edit_user')
        batch_op.drop_column('create_user')

    # ### end Alembic commands ###
