"""Add post related rights

Revision ID: 57b74656c425
Revises: 77491a835a83
Create Date: 2025-03-05 22:21:32.844437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b74656c425'
down_revision = '77491a835a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_post', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('edit_foreign_post', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delete_foreign_post', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.drop_column('delete_foreign_post')
        batch_op.drop_column('edit_foreign_post')
        batch_op.drop_column('create_post')

    # ### end Alembic commands ###
