"""Add start page messages

Revision ID: 77491a835a83
Revises: 480c47f070cd
Create Date: 2025-02-26 23:44:09.179148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77491a835a83'
down_revision = '480c47f070cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_to'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_answer_to'), ['answer_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_answer_to'))

    op.drop_table('post')
    # ### end Alembic commands ###
