"""Add event types

Revision ID: 94fd8b420f38
Revises: 3ff7a9ded819
Create Date: 2025-02-09 00:19:37.896287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fd8b420f38'
down_revision = '3ff7a9ded819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('school', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('special', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('misc', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.drop_column('misc')
        batch_op.drop_column('special')
        batch_op.drop_column('school')
        batch_op.drop_column('public')

    # ### end Alembic commands ###
