"""empty message

Revision ID: 999c889363a7
Revises: 35ad2406fa44
Create Date: 2026-02-05 10:57:52.741125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999c889363a7'
down_revision = '35ad2406fa44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_calendar_year', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.drop_column('edit_calendar_year')

    # ### end Alembic commands ###
