"""Recreate database

Revision ID: aaf2efdb7178
Revises: 
Create Date: 2026-04-05 01:15:58.585183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf2efdb7178'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('firstname', sa.String(length=256), nullable=True),
    sa.Column('lastname', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('is2fa_enabled', sa.Boolean(), nullable=False),
    sa.Column('token_2fa', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_2fa')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('calendar_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['calendar_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_entry_series_id'), ['series_id'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_to'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_answer_to'), ['answer_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    op.create_table('right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('login_allowed', sa.Boolean(), nullable=False),
    sa.Column('create_calendar_entry', sa.Boolean(), nullable=False),
    sa.Column('edit_calendar_year', sa.Boolean(), nullable=False),
    sa.Column('create_user', sa.Boolean(), nullable=False),
    sa.Column('edit_user', sa.Boolean(), nullable=False),
    sa.Column('delete_user', sa.Boolean(), nullable=False),
    sa.Column('edit_rights', sa.Boolean(), nullable=False),
    sa.Column('create_post', sa.Boolean(), nullable=False),
    sa.Column('edit_foreign_post', sa.Boolean(), nullable=False),
    sa.Column('delete_foreign_post', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_right_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('right', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_right_user_id'))

    op.drop_table('right')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_answer_to'))

    op.drop_table('post')
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_entry_series_id'))

    op.drop_table('calendar_entry')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('calendar_series')
    # ### end Alembic commands ###
